package org.indis.app.ui.verify

import android.graphics.Bitmap
import android.os.Bundle
import android.view.View
import android.widget.ArrayAdapter
import android.widget.Button
import android.widget.FrameLayout
import android.widget.ImageView
import android.widget.Spinner
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import com.google.zxing.BarcodeFormat
import com.google.zxing.EncodeHintType
import com.google.zxing.qrcode.QRCodeWriter
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.indis.app.R
import org.indis.app.domain.zk.ZKProofManager
import org.json.JSONObject

/**
 * Verification screen — generates a ZK proof QR code for presentation to a verifier terminal.
 *
 * The citizen selects a predicate (e.g. "age ≥ 18"), taps "Generate",
 * the [ZKProofManager] produces a proof (currently a stub; real WASM bridge TODO),
 * and the result is encoded as a QR code for the verifier to scan.
 *
 * PRD FR-007 (ZK proof generation), FR-008 (selective disclosure).
 * Verifier receives ONLY a boolean — no raw identity data is encoded in the QR.
 */
class VerifyActivity : AppCompatActivity() {

    private lateinit var spinnerPredicate: Spinner
    private lateinit var btnGenerateProof: Button
    private lateinit var frameQr: FrameLayout
    private lateinit var imgQrCode: ImageView
    private lateinit var tvQrHint: TextView
    private lateinit var tvStatus: TextView

    private val zkManager = ZKProofManager()

    private val predicates = listOf(
        "age_gte_18"          to "سن ≥ ۱۸ سال",
        "citizen"             to "تابعیت ایران",
        "voter_eligible"      to "واجد شرایط رأی‌گیری",
        "credential_valid"    to "اعتبارنامه معتبر است",
    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_verify)

        spinnerPredicate = findViewById(R.id.spinner_predicate)
        btnGenerateProof = findViewById(R.id.btn_generate_proof)
        frameQr          = findViewById(R.id.frame_qr)
        imgQrCode        = findViewById(R.id.img_qr_code)
        tvQrHint         = findViewById(R.id.tv_qr_hint)
        tvStatus         = findViewById(R.id.tv_status)

        spinnerPredicate.adapter = ArrayAdapter(
            this,
            android.R.layout.simple_spinner_item,
            predicates.map { it.second },
        ).also { it.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item) }

        btnGenerateProof.setOnClickListener { generateProof() }
    }

    private fun generateProof() {
        val selectedIdx = spinnerPredicate.selectedItemPosition
        val predicate   = predicates[selectedIdx].first

        tvStatus.text    = getString(R.string.verify_generating)
        frameQr.visibility  = View.GONE
        tvQrHint.visibility = View.GONE
        btnGenerateProof.isEnabled = false

        lifecycleScope.launch {
            val result = withContext(Dispatchers.Default) {
                runCatching {
                    // Build a minimal proof payload.
                    // TODO: replace stub bytes with real Groth16/Bulletproofs proof
                    // generated by the Rust WASM module once the JNI bridge is implemented.
                    val proofBytes = zkManager.verifyProof(predicate.toByteArray())
                    val nonce = java.util.UUID.randomUUID().toString().replace("-", "")

                    val payload = JSONObject().apply {
                        put("type",      "INDIS_ZK_PROOF")
                        put("predicate", predicate)
                        put("valid",     proofBytes)
                        put("nonce",     nonce)
                        put("ts",        System.currentTimeMillis())
                    }.toString()

                    encodeQR(payload, 512)
                }
            }

            btnGenerateProof.isEnabled = true

            result.fold(
                onSuccess = { bitmap ->
                    imgQrCode.setImageBitmap(bitmap)
                    frameQr.visibility  = View.VISIBLE
                    tvQrHint.visibility = View.VISIBLE
                    tvStatus.text       = ""
                },
                onFailure = { err ->
                    tvStatus.text = err.message ?: getString(R.string.verify_error)
                },
            )
        }
    }

    private fun encodeQR(content: String, sizePx: Int): Bitmap {
        val writer = QRCodeWriter()
        val hints  = mapOf(EncodeHintType.CHARACTER_SET to "UTF-8")
        val matrix = writer.encode(content, BarcodeFormat.QR_CODE, sizePx, sizePx, hints)

        val bitmap = Bitmap.createBitmap(sizePx, sizePx, Bitmap.Config.RGB_565)
        for (x in 0 until sizePx) {
            for (y in 0 until sizePx) {
                bitmap.setPixel(x, y, if (matrix[x, y]) 0xFF000000.toInt() else 0xFFFFFFFF.toInt())
            }
        }
        return bitmap
    }
}
