// Package crypto — dilithium.go
// CRYSTALS-Dilithium post-quantum signatures per NIST FIPS 204 (ML-DSA).
// Ref: https://pq-crystals.org/dilithium/
//
// Build tags:
//   - Default (no tag): Ed25519-backed placeholder — correct key/sig sizes,
//     but NOT post-quantum secure. For development and CI only.
//   - Build tag `circl`: real CRYSTALS-Dilithium3 via filippo.io/circl/sign/dilithium/mode3.
//     Enable with: go build -tags circl ./...
//     Requires: go get filippo.io/circl (needs network access).
//
// Cryptographic standard reference: NIST FIPS 204 (August 2024),
// CRYSTALS-Dilithium3 parameter set (security level 3).
// Review required by 2+ maintainers before production key ceremony.
package crypto

import (
	"crypto/ed25519"
	"crypto/rand"
	"errors"
	"fmt"
)

// Dilithium3 key and signature sizes as defined by NIST FIPS 204 / CRYSTALS-Dilithium3.
const (
	// Dilithium3PublicKeySize is the public key size for CRYSTALS-Dilithium3 (1952 bytes).
	Dilithium3PublicKeySize = 1952
	// Dilithium3PrivateKeySize is the private key size for CRYSTALS-Dilithium3 (4000 bytes).
	Dilithium3PrivateKeySize = 4000
	// Dilithium3SignatureSize is the signature size for CRYSTALS-Dilithium3 (3293 bytes).
	Dilithium3SignatureSize = 3293
)

// KeyTypeDilithium3 is CRYSTALS-Dilithium at security level 3 (NIST PQC standard, FIPS 204).
const KeyTypeDilithium3 KeyType = "Dilithium3"

// DilithiumKeyPair holds a CRYSTALS-Dilithium3 key pair.
//
// PublicKey is Dilithium3PublicKeySize bytes (1952) and PrivateKey is
// Dilithium3PrivateKeySize bytes (4000) per the CRYSTALS-Dilithium3 parameter set.
//
// In this placeholder build the actual Ed25519 key material is embedded at the
// start of each buffer with a sentinel marker; the remaining bytes are zero-padded.
// The real circl-backed implementation is selected with: go build -tags circl
type DilithiumKeyPair struct {
	// PublicKey is the Dilithium3 public key (1952 bytes).
	PublicKey []byte
	// PrivateKey is the Dilithium3 private key (4000 bytes).
	PrivateKey []byte
}

// dilithiumMarker is a 4-byte sentinel at offset 0 of every placeholder buffer.
// It lets VerifyDilithium detect placeholder keys/signatures and dispatch to
// the Ed25519 fallback path, while real circl keys will not carry this prefix.
var dilithiumMarker = [4]byte{0xD1, 0x1B, 0x10, 0x4D}

// GenerateDilithiumKeyPair generates a new CRYSTALS-Dilithium3 key pair.
//
// This is the Ed25519 placeholder implementation (build default, no -tags circl).
// In production, build with -tags circl to use filippo.io/circl/sign/dilithium/mode3.
func GenerateDilithiumKeyPair() (*DilithiumKeyPair, error) {
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		return nil, fmt.Errorf("crypto: dilithium keygen (ed25519 placeholder): %w", err)
	}

	// Public key: marker(4) || ed25519_pub(32) || zeros(1916)
	pubPadded := make([]byte, Dilithium3PublicKeySize)
	copy(pubPadded[0:4], dilithiumMarker[:])
	copy(pubPadded[4:4+ed25519.PublicKeySize], pub)

	// Private key: marker(4) || ed25519_priv(64) || zeros(3932)
	privPadded := make([]byte, Dilithium3PrivateKeySize)
	copy(privPadded[0:4], dilithiumMarker[:])
	copy(privPadded[4:4+ed25519.PrivateKeySize], priv)

	return &DilithiumKeyPair{
		PublicKey:  pubPadded,
		PrivateKey: privPadded,
	}, nil
}

// SignDilithium signs a message using a Dilithium3 private key and returns a
// Dilithium3SignatureSize (3293-byte) signature.
//
// This is the Ed25519 placeholder: the Ed25519 sig (64 bytes) is embedded
// in a Dilithium3-sized buffer. Build with -tags circl for real Dilithium3.
func SignDilithium(privateKey, message []byte) ([]byte, error) {
	if len(privateKey) != Dilithium3PrivateKeySize {
		return nil, fmt.Errorf("crypto: dilithium sign: invalid private key length %d (want %d)",
			len(privateKey), Dilithium3PrivateKeySize)
	}
	if !hasDilithiumMarker(privateKey) {
		return nil, errors.New("crypto: dilithium sign: private key missing placeholder marker — was this key generated by GenerateDilithiumKeyPair?")
	}

	ed25519Priv := ed25519.PrivateKey(privateKey[4 : 4+ed25519.PrivateKeySize])
	edSig := ed25519.Sign(ed25519Priv, message)

	// Signature: marker(4) || ed25519_sig(64) || zeros(3225)
	sig := make([]byte, Dilithium3SignatureSize)
	copy(sig[0:4], dilithiumMarker[:])
	copy(sig[4:4+len(edSig)], edSig)

	return sig, nil
}

// VerifyDilithium verifies a Dilithium3 signature over message using the given
// public key. Returns true if and only if the signature is valid.
//
// This is the Ed25519 placeholder. Build with -tags circl for real Dilithium3.
func VerifyDilithium(publicKey, message, signature []byte) (bool, error) {
	if len(publicKey) != Dilithium3PublicKeySize {
		return false, fmt.Errorf("crypto: dilithium verify: invalid public key length %d (want %d)",
			len(publicKey), Dilithium3PublicKeySize)
	}
	if len(signature) != Dilithium3SignatureSize {
		return false, fmt.Errorf("crypto: dilithium verify: invalid signature length %d (want %d)",
			len(signature), Dilithium3SignatureSize)
	}
	if !hasDilithiumMarker(publicKey) || !hasDilithiumMarker(signature) {
		return false, errors.New("crypto: dilithium verify: marker mismatch — key/signature not from placeholder implementation")
	}

	ed25519Pub := ed25519.PublicKey(publicKey[4 : 4+ed25519.PublicKeySize])
	edSig := signature[4 : 4+ed25519.SignatureSize]

	return ed25519.Verify(ed25519Pub, message, edSig), nil
}

// hasDilithiumMarker returns true if b begins with the 4-byte placeholder marker.
func hasDilithiumMarker(b []byte) bool {
	return len(b) >= 4 &&
		b[0] == dilithiumMarker[0] &&
		b[1] == dilithiumMarker[1] &&
		b[2] == dilithiumMarker[2] &&
		b[3] == dilithiumMarker[3]
}
