apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ai
  labels:
    app: ai
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: grpc
      name: grpc
    - port: 9090
      targetPort: metrics
      name: metrics
  selector:
    app: ai
