apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.domain | replace "." "-" }}-credential
  labels:
    app: credential
spec:
  replicas: {{ .Values.credential.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: credential
  template:
    metadata:
      labels:
        app: credential
    spec:
      containers:
        - name: credential
          image: "{{ .Values.credential.image.repository }}:{{ .Values.credential.image.tag }}"
          imagePullPolicy: {{ .Values.credential.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 9090
              name: metrics
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-credential-config
          resources:
            {{- toYaml .Values.credential.resources | nindent 12 }}
