apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-verifier
  labels:
    app: verifier
spec:
  type: ClusterIP
  ports:
    - port: 9110
      targetPort: grpc
      name: grpc
    - port: 9111
      targetPort: metrics
      name: metrics
  selector:
    app: verifier
