apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.domain | replace "." "-" }}-ussd
  labels:
    app: ussd
spec:
  replicas: {{ .Values.ussd.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: ussd
  template:
    metadata:
      labels:
        app: ussd
    spec:
      containers:
        - name: ussd
          image: "{{ .Values.ussd.image.repository }}:{{ .Values.ussd.image.tag }}"
          imagePullPolicy: {{ .Values.ussd.image.pullPolicy }}
          ports:
            - containerPort: 8300
              name: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-ussd-config
          resources:
            {{- toYaml .Values.ussd.resources | nindent 12 }}
