apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-govportal-config
data:
  HTTP_PORT: "8200"
  METRICS_PORT: "8201"
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  DATABASE_URL: "postgres://indis:indis@{{ .Values.global.postgres.host }}:{{ .Values.global.postgres.port }}/indis_govportal?sslmode=disable"
  REDIS_URL: "redis://{{ .Values.global.redis.host }}:{{ .Values.global.redis.port }}"
  KAFKA_BROKERS: "{{ .Values.global.kafka.brokers }}"
